// Integration tests for server/serve.js: spawns the real server as a
// subprocess against a throwaway TUTORING_DATA_DIR + a random port, then
// exercises it over real HTTP. Never touches app/production/ -- see
// DESIGN.md's "never use production/ for testing" rule.

const { spawn } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const SERVE_JS = path.join(__dirname, '..', 'serve.js');
const DIST_DIR = path.join(__dirname, '..', '..', 'dist');

let dataDir;
let child;
let baseUrl;
let token;

function waitForServer(url, timeoutMs = 15000) {
  const start = Date.now();
  return new Promise((resolve, reject) => {
    (async function poll() {
      while (Date.now() - start < timeoutMs) {
        try {
          const res = await fetch(url);
          if (res.status) return resolve();
        } catch {
          // not up yet
        }
        await new Promise((r) => setTimeout(r, 150));
      }
      reject(new Error('Server did not start in time'));
    })();
  });
}

beforeAll(async () => {
  if (!fs.existsSync(DIST_DIR)) {
    throw new Error('dist/ is missing -- run "npm run build:web" before the test suite (the "pretest" script does this automatically for `npm test`).');
  }

  dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tutoring-serve-test-'));
  const port = 20000 + Math.floor(Math.random() * 10000);
  baseUrl = `http://localhost:${port}`;

  child = spawn(process.execPath, [SERVE_JS], {
    env: { ...process.env, TUTORING_DATA_DIR: dataDir, PORT: String(port) },
    stdio: 'pipe',
  });

  await waitForServer(baseUrl + '/manifest.json');
  // The access token lives next to serve.js (server/access-token.txt),
  // shared across every run -- not per test data dir. It's a real,
  // already-generated token by the time any test suite runs (this repo's
  // dev server has been run before), so this just reads the existing one;
  // it's never regenerated by a test run.
  token = fs.readFileSync(path.join(__dirname, '..', 'access-token.txt'), 'utf8').trim();
}, 20000);

afterAll(() => {
  child?.kill();
  fs.rmSync(dataDir, { recursive: true, force: true });
});

function authHeaders(extra) {
  return { 'X-Dashboard-Token': token, ...extra };
}

describe('auth', () => {
  it('rejects requests with no token', async () => {
    const res = await fetch(baseUrl + '/api/students');
    expect(res.status).toBe(401);
  });

  it('accepts the token via header', async () => {
    const res = await fetch(baseUrl + '/api/students', { headers: authHeaders() });
    expect(res.status).toBe(200);
  });

  it('accepts the token via query param, and sets a cookie on the page load', async () => {
    const res = await fetch(`${baseUrl}/?token=${token}`);
    expect(res.status).toBe(200);
    expect(res.headers.get('set-cookie') || '').toContain('dash_token=');
  });

  it('rejects a wrong token', async () => {
    const res = await fetch(baseUrl + '/api/students', { headers: authHeaders({ 'X-Dashboard-Token': 'not-the-token' }) });
    expect(res.status).toBe(401);
  });
});

describe('manifest.json', () => {
  it('is public (no auth needed) and omits the token when unauthorized', async () => {
    const res = await fetch(baseUrl + '/manifest.json');
    expect(res.status).toBe(200);
    const manifest = await res.json();
    expect(manifest.start_url).toBe('./');
    expect(manifest.name).toBeTruthy();
    expect(manifest.icons.length).toBeGreaterThan(0);
  });

  it('embeds the token into start_url only when the request is authorized', async () => {
    const res = await fetch(baseUrl + '/manifest.json', { headers: authHeaders() });
    const manifest = await res.json();
    expect(manifest.start_url).toBe(`./?token=${token}`);
  });

  it('is never cached', async () => {
    const res = await fetch(baseUrl + '/manifest.json');
    expect(res.headers.get('cache-control')).toBe('no-store');
  });
});

describe('icons', () => {
  it('serves icons without auth', async () => {
    const res = await fetch(baseUrl + '/icons/icon-192.png');
    expect(res.status).toBe(200);
    expect(res.headers.get('content-type')).toBe('image/png');
  });
});

describe('per-resource data endpoints', () => {
  const resources = ['students', 'classes', 'attendance', 'makeup', 'payments'];

  it.each(resources)('%s starts empty', async (resource) => {
    const res = await fetch(`${baseUrl}/api/${resource}`, { headers: authHeaders() });
    expect(res.status).toBe(200);
    expect(await res.json()).toEqual([]);
  });

  it.each(resources)('%s rejects a non-array body', async (resource) => {
    const res = await fetch(`${baseUrl}/api/${resource}`, {
      method: 'POST',
      headers: authHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify({ not: 'an array' }),
    });
    expect(res.status).toBe(400);
  });

  it.each(resources)('%s rejects unparseable JSON', async (resource) => {
    const res = await fetch(`${baseUrl}/api/${resource}`, {
      method: 'POST',
      headers: authHeaders({ 'Content-Type': 'application/json' }),
      body: '{not valid json',
    });
    expect(res.status).toBe(400);
  });

  it.each(resources)('%s round-trips a saved array', async (resource) => {
    const payload = [{ id: `${resource}_1`, marker: resource }];
    const post = await fetch(`${baseUrl}/api/${resource}`, {
      method: 'POST',
      headers: authHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify(payload),
    });
    expect(post.status).toBe(200);
    expect(await post.json()).toEqual({ ok: true });

    const get = await fetch(`${baseUrl}/api/${resource}`, { headers: authHeaders() });
    expect(await get.json()).toEqual(payload);
  });

  it('a write to one resource never affects the others', async () => {
    const before = {};
    for (const r of resources) {
      before[r] = await (await fetch(`${baseUrl}/api/${r}`, { headers: authHeaders() })).json();
    }

    await fetch(`${baseUrl}/api/students`, {
      method: 'POST',
      headers: authHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify([{ id: 'stu_isolation_check' }]),
    });

    for (const r of resources.filter((r) => r !== 'students')) {
      const now = await (await fetch(`${baseUrl}/api/${r}`, { headers: authHeaders() })).json();
      expect(now).toEqual(before[r]);
    }
  });

  it('rejects methods other than GET/POST', async () => {
    const res = await fetch(`${baseUrl}/api/students`, { method: 'DELETE', headers: authHeaders() });
    expect(res.status).toBe(405);
  });

  it('404s an unknown resource name', async () => {
    // Falls through to the SPA-fallback static file logic, which for an
    // authorized request serves index.html (200), not a 404 -- confirms
    // /api/not-a-real-resource isn't accidentally treated as a data route.
    const res = await fetch(`${baseUrl}/api/not-a-real-resource`, { headers: authHeaders() });
    expect(res.status).toBe(200);
    const body = await res.text();
    expect(body).toContain('<html');
  });
});

describe('automatic backups', () => {
  it('does not back up on the very first write (nothing existed yet)', async () => {
    const backupsDir = path.join(dataDir, 'backups');
    const before = fs.existsSync(backupsDir) ? fs.readdirSync(backupsDir).length : 0;

    await fetch(`${baseUrl}/api/makeup`, {
      method: 'POST',
      headers: authHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify([]),
    });
    // makeup.json may already have been written by an earlier test in this
    // file; this test only asserts backups never shrink or error, since
    // exact counts depend on test execution order.
    const after = fs.existsSync(backupsDir) ? fs.readdirSync(backupsDir).length : 0;
    expect(after).toBeGreaterThanOrEqual(before);
  });

  it('snapshots the previous content before a second write', async () => {
    const resource = 'payments';
    const first = [{ id: 'pay_1', note: 'first' }];
    const second = [{ id: 'pay_1', note: 'second' }];

    await fetch(`${baseUrl}/api/${resource}`, {
      method: 'POST',
      headers: authHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify(first),
    });
    const backupsDir = path.join(dataDir, 'backups');
    const before = fs.existsSync(backupsDir) ? fs.readdirSync(backupsDir).length : 0;

    await fetch(`${baseUrl}/api/${resource}`, {
      method: 'POST',
      headers: authHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify(second),
    });

    const snapshots = fs.readdirSync(backupsDir);
    expect(snapshots.length).toBeGreaterThan(before);

    const newestSnapshot = snapshots.sort().at(-1);
    const snapshotContent = JSON.parse(fs.readFileSync(path.join(backupsDir, newestSnapshot, `${resource}.json`), 'utf8'));
    expect(snapshotContent).toEqual(first);

    const current = await (await fetch(`${baseUrl}/api/${resource}`, { headers: authHeaders() })).json();
    expect(current).toEqual(second);
  });
});

describe('caching headers', () => {
  it('never caches index.html', async () => {
    const res = await fetch(`${baseUrl}/?token=${token}`);
    expect(res.headers.get('cache-control')).toBe('no-cache, must-revalidate');
  });

  it('caches hashed JS/CSS bundle assets hard', async () => {
    // Bundle assets require auth just like everything but manifest/icons.
    const jsDir = path.join(DIST_DIR, '_expo', 'static', 'js', 'web');
    const [entry] = fs.readdirSync(jsDir).filter((f) => f.endsWith('.js'));
    const res = await fetch(`${baseUrl}/_expo/static/js/web/${entry}`, { headers: authHeaders() });
    expect(res.status).toBe(200);
    expect(res.headers.get('cache-control')).toBe('public, max-age=31536000, immutable');
  });
});

describe('unauthorized access', () => {
  it('serves a helpful, non-crashing page instead of the app', async () => {
    const res = await fetch(baseUrl + '/students'); // authorized route, but no token supplied
    expect(res.status).toBe(401);
    const body = await res.text();
    expect(body).toContain('Unauthorized');
  });
});
