// Integration tests for server/serve.js: spawns the real server as a
// subprocess against a throwaway TUTORING_DATA_DIR + a random port, then
// exercises it over real HTTP. Never touches app/production/ -- see
// DESIGN.md's "never use production/ for testing" rule.

const { spawn } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const SERVE_JS = path.join(__dirname, '..', 'serve.js');
const DIST_DIR = path.join(__dirname, '..', '..', 'dist');

let dataDir;
let child;
let baseUrl;
let token;

function waitForServer(url, timeoutMs = 15000) {
  const start = Date.now();
  return new Promise((resolve, reject) => {
    (async function poll() {
      while (Date.now() - start < timeoutMs) {
        try {
          const res = await fetch(url);
          if (res.status) return resolve();
        } catch {
          // not up yet
        }
        await new Promise((r) => setTimeout(r, 150));
      }
      reject(new Error('Server did not start in time'));
    })();
  });
}

beforeAll(async () => {
  if (!fs.existsSync(DIST_DIR)) {
    throw new Error('dist/ is missing -- run "npm run build:web" before the test suite (the "pretest" script does this automatically for `npm test`).');
  }

  dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tutoring-serve-test-'));
  const port = 20000 + Math.floor(Math.random() * 10000);
  baseUrl = `http://localhost:${port}`;

  child = spawn(process.execPath, [SERVE_JS], {
    env: { ...process.env, TUTORING_DATA_DIR: dataDir, PORT: String(port) },
    stdio: 'pipe',
  });

  await waitForServer(baseUrl + '/manifest.json');
  // The access token lives next to serve.js (server/access-token.txt),
  // shared across every run -- not per test data dir. It's a real,
  // already-generated token by the time any test suite runs (this repo's
  // dev server has been run before), so this just reads the existing one;
  // it's never regenerated by a test run.
  token = fs.readFileSync(path.join(__dirname, '..', 'access-token.txt'), 'utf8').trim();
}, 20000);

afterAll(() => {
  child?.kill();
  fs.rmSync(dataDir, { recursive: true, force: true });
});

function authHeaders(extra) {
  return { 'X-Dashboard-Token': token, ...extra };
}

describe('auth', () => {
  it('rejects requests with no token', async () => {
    const res = await fetch(baseUrl + '/api/students');
    expect(res.status).toBe(401);
  });

  it('accepts the token via header', async () => {
    const res = await fetch(baseUrl + '/api/students', { headers: authHeaders() });
    expect(res.status).toBe(200);
  });

  it('accepts the token via query param, and sets a cookie on the page load', async () => {
    const res = await fetch(`${baseUrl}/?token=${token}`);
    expect(res.status).toBe(200);
    expect(res.headers.get('set-cookie') || '').toContain('dash_token=');
  });

  it('rejects a wrong token', async () => {
    const res = await fetch(baseUrl + '/api/students', { headers: authHeaders({ 'X-Dashboard-Token': 'not-the-token' }) });
    expect(res.status).toBe(401);
  });
});

describe('manifest.json', () => {
  it('is public (no auth needed) and omits the token when unauthorized', async () => {
    const res = await fetch(baseUrl + '/manifest.json');
    expect(res.status).toBe(200);
    const manifest = await res.json();
    expect(manifest.start_url).toBe('./');
    expect(manifest.name).toBeTruthy();
    expect(manifest.icons.length).toBeGreaterThan(0);
  });

  it('embeds the token into start_url only when the request is authorized', async () => {
    const res = await fetch(baseUrl + '/manifest.json', { headers: authHeaders() });
    const manifest = await res.json();
    expect(manifest.start_url).toBe(`./?token=${token}`);
  });

  it('is never cached', async () => {
    const res = await fetch(baseUrl + '/manifest.json');
    expect(res.headers.get('cache-control')).toBe('no-store');
  });
});

describe('icons', () => {
  it('serves icons without auth', async () => {
    const res = await fetch(baseUrl + '/icons/icon-192.png');
    expect(res.status).toBe(200);
    expect(res.headers.get('content-type')).toBe('image/png');
  });
});

describe('data endpoints', () => {
  const resources = ['students', 'classes', 'sessions', 'payments'];
  const api = (p, init = {}) =>
    fetch(`${baseUrl}/api/${p}`, { ...init, headers: authHeaders({ 'Content-Type': 'application/json' }) });
  const put = (resource, id, record, baseVersion) =>
    api(`${resource}/${encodeURIComponent(id)}`, { method: 'PUT', body: JSON.stringify({ record, baseVersion }) });
  const del = (resource, id, baseVersion) =>
    api(`${resource}/${encodeURIComponent(id)}`, { method: 'DELETE', body: JSON.stringify({ baseVersion }) });
  const list = async (resource) => (await api(resource)).json();

  const student = (id, extra = {}) => ({
    id,
    name: `Student ${id}`,
    grade: '3',
    parentName: 'Priya',
    parentPhone: '15551234567',
    ratePerSession: 30,
    active: true,
    createdAt: '2026-09-01T00:00:00.000Z',
    ...extra,
  });

  it.each(resources)('%s starts empty', async (resource) => {
    const res = await api(resource);
    expect(res.status).toBe(200);
    expect(await res.json()).toEqual([]);
  });

  it('saves one record at a time, returning its version, and lists it with _version', async () => {
    const res = await put('students', 'stu_a', student('stu_a'), null);
    expect(res.status).toBe(200);
    expect(await res.json()).toEqual({ ok: true, version: 1 });
    expect(await list('students')).toEqual([{ ...student('stu_a'), _version: 1 }]);

    const update = await put('students', 'stu_a', student('stu_a', { name: 'Ava' }), 1);
    expect(await update.json()).toEqual({ ok: true, version: 2 });
  });

  it('answers 409 with the newer copy when a save is based on an old version -- nothing overwritten', async () => {
    await put('students', 'stu_b', student('stu_b'), null);
    await put('students', 'stu_b', student('stu_b', { name: 'From phone' }), 1);

    const stale = await put('students', 'stu_b', student('stu_b', { name: 'From laptop' }), 1);
    expect(stale.status).toBe(409);
    expect(await stale.json()).toMatchObject({ ok: false, conflict: true, version: 2, current: { name: 'From phone' } });
    expect((await list('students')).find((s) => s.id === 'stu_b').name).toBe('From phone');
  });

  it('deletes with the same version check', async () => {
    await put('students', 'stu_del', student('stu_del'), null);
    expect((await del('students', 'stu_del', 99)).status).toBe(409);
    expect((await del('students', 'stu_del', 1)).status).toBe(200);
    expect((await list('students')).some((s) => s.id === 'stu_del')).toBe(false);
  });

  it('handles ids with characters like ":" (session ids contain times)', async () => {
    await put('classes', 'grp_1', {
      id: 'grp_1', name: 'Tue', type: 'one-on-one', studentIds: ['stu_a'],
      schedule: [{ dayOfWeek: 2, startTime: '16:00', durationMinutes: 60 }], active: true, createdAt: '2026-09-01',
    }, null);
    const id = 'grp_1_2026-09-08_16:00';
    const res = await put('sessions', id, {
      id, date: '2026-09-08', startTime: '16:00', durationMinutes: 60, groupId: 'grp_1', isMakeup: false,
      studentIds: ['stu_a'], attendance: { stu_a: 'present' }, createdAt: '2026-09-08',
    }, null);
    expect(res.status).toBe(200);
    expect((await list('sessions')).map((s) => s.id)).toContain(id);
  });

  it('rejects malformed records, broken links, bad JSON, and a mismatched id with 400', async () => {
    expect((await put('students', 'x', { id: 'x' }, null)).status).toBe(400);
    expect((await put('payments', 'p', {
      id: 'p', studentId: 'no-such-student', month: '2026-09', amountDue: 1, amountPaid: 0, status: 'unpaid', createdAt: 'x',
    }, null)).status).toBe(400);
    expect((await api('students/x', { method: 'PUT', body: '{not json' })).status).toBe(400);
    expect((await put('students', 'y', student('z'), null)).status).toBe(400);
  });

  it('refuses the old "replace the whole list" saves (410), so an out-of-date app can never overwrite anything', async () => {
    const before = await list('students');
    for (const legacy of ['students', 'classes', 'attendance', 'makeup', 'payments']) {
      const res = await api(legacy, { method: 'POST', body: JSON.stringify([]) });
      expect(res.status).toBe(410);
      expect((await res.json()).error).toMatch(/reload/i);
    }
    expect(await list('students')).toEqual(before);
  });

  it('still answers old attendance/makeup reads, from sessions', async () => {
    const attendance = await list('attendance');
    expect(attendance.every((s) => s.isMakeup === false)).toBe(true);
    expect(attendance.length).toBeGreaterThan(0);
    expect(await list('makeup')).toEqual([]);
  });

  it('rejects other methods', async () => {
    expect((await api('students', { method: 'DELETE' })).status).toBe(405);
    expect((await api('students/stu_a', { method: 'POST', body: '{}' })).status).toBe(405);
  });

  it('does not treat an unknown resource as a data route', async () => {
    // Falls through to the SPA-fallback static file logic, which for an
    // authorized request serves index.html (200).
    const res = await fetch(`${baseUrl}/api/not-a-real-resource`, { headers: authHeaders() });
    expect(res.status).toBe(200);
    expect(await res.text()).toContain('<html');
  });

  describe('automatic backups', () => {
    it('snapshots the database before a save, capturing the previous content', async () => {
      const backupsDir = path.join(dataDir, 'backups');
      const before = fs.existsSync(backupsDir) ? fs.readdirSync(backupsDir).length : 0;
      await put('students', 'stu_snap', student('stu_snap', { name: 'first' }), null);
      await put('students', 'stu_snap', student('stu_snap', { name: 'second' }), 1);

      const snapshots = fs.readdirSync(backupsDir).sort();
      expect(snapshots.length).toBeGreaterThan(before);

      const { DatabaseSync } = require('node:sqlite');
      const snap = new DatabaseSync(path.join(backupsDir, snapshots.at(-1)), { readOnly: true });
      expect(snap.prepare("SELECT name FROM students WHERE id = 'stu_snap'").get().name).toBe('first');
      snap.close();
    });
  });
});

describe('caching headers', () => {
  it('never caches index.html', async () => {
    const res = await fetch(`${baseUrl}/?token=${token}`);
    expect(res.headers.get('cache-control')).toBe('no-cache, must-revalidate');
  });

  it('caches hashed JS/CSS bundle assets hard', async () => {
    // Bundle assets require auth just like everything but manifest/icons.
    const jsDir = path.join(DIST_DIR, '_expo', 'static', 'js', 'web');
    const [entry] = fs.readdirSync(jsDir).filter((f) => f.endsWith('.js'));
    const res = await fetch(`${baseUrl}/_expo/static/js/web/${entry}`, { headers: authHeaders() });
    expect(res.status).toBe(200);
    expect(res.headers.get('cache-control')).toBe('public, max-age=31536000, immutable');
  });
});

describe('unauthorized access', () => {
  it('serves a helpful, non-crashing page instead of the app', async () => {
    const res = await fetch(baseUrl + '/students'); // authorized route, but no token supplied
    expect(res.status).toBe(401);
    const body = await res.text();
    expect(body).toContain('Unauthorized');
  });
});
